name: Deploy with Ansible

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create inventory from secrets
        run: |
          echo "[server]" > inventory.ini
          echo "target ansible_host=${{ secrets.ANSIBLE_HOST }} ansible_user=${{ secrets.ANSIBLE_USER }} ansible_python_interpreter=/usr/bin/python3" >> inventory.ini

      - name: Export environment variables for Ansible
        run: |
          echo "SSH_MAIN_USER=${{ secrets.SSH_MAIN_USER }}" >> $GITHUB_ENV
          echo "SSH_MAIN_PUBKEY=${{ secrets.SSH_MAIN_PUBKEY }}" >> $GITHUB_ENV
          echo "SSH_BACKUP_USER=${{ secrets.SSH_BACKUP_USER }}" >> $GITHUB_ENV
          echo "SSH_BACKUP_PUBKEY=${{ secrets.SSH_BACKUP_PUBKEY }}" >> $GITHUB_ENV

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/playbook.yml -i inventory.ini